resource_types:
- name: boshdir
  type: docker-image
  source: {repository: concourse/github-pr-space-type}

resources:
- name: director
  type: boshdir
  source:
    target: bosh.concourse-ci.org
    client_id: abc
    client_secret: def

- name: release
  type: git
  source:
    uri: https://github.com/concourse/concourse
    branch: master

- name: deployment
  type: git
  source:
    uri: https://github.com/concourse/concourse-bosh-deployment
    branch: master

jobs:
- name: unit
  plan:
  - get: release
    trigger: true
  - task: unit
    file: release/ci/unit.yml

- name: deploy
  plan:
  - get: release
    passed: [unit]
    trigger: true
  - get: deployment
    trigger: true
  - task: create-rc
    file: release/ci/create.yml
  - put: director
    params:
      manifest: deployment/cluster/concourse.yml
      releases: [release-rc/*.tgz]

- name: acceptance
  plan:
  - get: release
    passed: [deploy]
    trigger: true
  - get: deployment
    passed: [deploy]
    trigger: true
  - get: director
    passed: [deploy]
