resources:
- name: atc
  type: git
  source: {uri: https://github.com/concourse/atc}
  space: master

- name: atc-gen
  type: git
  source: {uri: "https://github.com/concourse/atc"}

jobs:
- name: gen
  plan:
  - get: atc
    trigger: true
  - task: gen
    file: atc/ci/gen.yml
    config:
      platform: ...
      image_resource: ...
      outputs:
      - name: generated-repo
        # has the generated code committed to the repo
      - name: branch-name
        # has a 'name' file with `gen-(some deterministic hash)`
  - put: atc-gen
    params: {branch_name: branch-name/name, repository: generated-repo}

- name: test
  plan:
  - get: atc
    passed: [gen]
    trigger: true
  - get: atc-gen
    passed: [gen]
    spaces: [gen-*]
    trigger: true
  - task: test
    file: atc/ci/test.yml
