resource_types:
- name: slack-notifier
  type: docker-image
  source: {repository: concourse/slack-notifier-resource}

resources:
- name: atc
  type: git
  source:
    uri: https://github.com/concourse/atc

- name: slack-alert
  type: slack-notifier
  source:
    url: https://hooks.slack.com/services/XXXX
  notify:
  - on: build_finished
    params:
      template:
        succeeded: |
          Yay! <{{.ExternalURL}}/builds/{{.BuildID}}|{{.BuildName}}> succeeded. :)
        failed: |
          Oh no! <{{.ExternalURL}}/builds/{{.BuildID}}|{{.BuildName}}> failed. :(

jobs:
- name: atc-pr-unit
  plan:
  - get: atc-pr
    trigger: true
    spaces: all
  - task: unit
    file: atc/ci/pr.yml
