resource_types:
- name: github-pr
  type: docker-image
  source: {repository: concourse/github-pr-resource}

resources:
- name: atc-pr
  type: github-pr
  source:
    repository: concourse/atc
    access_token: ((token))

jobs:
- name: atc-pr-unit
  plan:
  - get: atc-pr
    trigger: true
    spaces: all
  - task: unit
    file: atc/ci/pr.yml

  # TODO: this currently doesn't do any commit status indication
